package org.nem.nis.poi;

public enum RemoteStatus {
	NOT_SET,

	OWNER_INACTIVE,
	OWNER_ACTIVATING,
	OWNER_ACTIVE,
	OWNER_DEACTIVATING,
	REMOTE_INACTIVE,
	REMOTE_ACTIVATING,
	REMOTE_ACTIVE,
	REMOTE_DEACTIVATING,
}
