defaultCiPipeline {
	// First OS is the default for CI
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	environment = 'golang'

	packageId = 'gocrypto'

	codeCoverageTool = 'golang'
	minimumCodeCoverage = 86
}
