version: 2
updates:

  - package-ecosystem: gomod
    directory: /gocrpyto
    schedule:
      interval: weekly
      day: saturday
    target-branch: dev
    labels: [gocrypto]
    commit-message:
      prefix: '[dependency]'
    groups:
      core-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: maven
    directory: /core
    schedule:
      interval: weekly
      day: saturday
    target-branch: dev
    labels: [core]
    commit-message:
      prefix: '[dependency]'
    groups:
      core-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: maven
    directory: /deploy
    schedule:
      interval: weekly
      day: saturday
    target-branch: dev
    labels: [deploy]
    commit-message:
      prefix: '[dependency]'
    groups:
      deploy-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: maven
    directory: /nis
    schedule:
      interval: weekly
      day: saturday
    target-branch: dev
    labels: [nis]
    commit-message:
      prefix: '[dependency]'
    groups:
      nis-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: maven
    directory: /peer
    schedule:
      interval: weekly
      day: saturday
    target-branch: dev
    labels: [peer]
    commit-message:
      prefix: '[dependency]'
    groups:
      peer-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
    target-branch: dev
    commit-message:
      prefix: '[dependency]'
    groups:
      github-action-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
