version: 2
updates:

  - package-ecosystem: maven
    directory: /core
    schedule:
      interval: weekly
      day: saturday
    target-branch: dev
    labels: [core]
    commit-message:
      prefix: '[dependency]'

  - package-ecosystem: maven
    directory: /deploy
    schedule:
      interval: weekly
      day: saturday
    target-branch: dev
    labels: [deploy]
    commit-message:
      prefix: '[dependency]'

  - package-ecosystem: maven
    directory: /nis
    schedule:
      interval: weekly
      day: saturday
    target-branch: dev
    labels: [nis]
    commit-message:
      prefix: '[dependency]'

  - package-ecosystem: maven
    directory: /peer
    schedule:
      interval: weekly
      day: saturday
    target-branch: dev
    labels: [peer]
    commit-message:
      prefix: '[dependency]'
