defaultCiPipeline {
	platform = ['ubuntu']
    ciBuildDockerfile = 'java.Dockerfile'

	publisher = 'docker'
	dockerImageName = 'nemofficial/nis-client'

	dockerBuildArgs = "--build-arg GIT_BRANCH_NAME=$BRANCH_NAME ."

	packageId = 'nem-infra'
}
