language: java

jdk: openjdk8

install:
  - pushd .
  - mkdir .nemdeps
  - cd .nemdeps
  - git clone https://github.com/NemProject/nem.core.git
  - cd nem.core
  - git checkout dev
  - mvn install -DskipTests=true
  - popd
