defaultCiPipeline {
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	ciBuildDockerfile = 'java.Dockerfile'

	packageId = 'nem-core'

	codeCoverageTool = 'jacoco'

	discordWebHookUrlId = 'CLIENT_DISCORD_WEB_HOOK_URL_ID'
}
