DROP INDEX IF EXISTS IDX_ACCOUNTS_PRINTABLEKEY;
DROP INDEX IF EXISTS IDX_TRANSFERS_TRANSFERHASH;
DROP INDEX IF EXISTS IDX_TRANSFERS_SHORT_ID;
DROP INDEX IF EXISTS IDX_IMPORTANCETRANSFERS_TRANSFERHASH;
DROP INDEX IF EXISTS IDX_IMPORTANCETRANSFERS_SHORT_ID;
DROP INDEX IF EXISTS IDX_BLOCKS_BLOCKHASH;
