defaultCiPipeline {
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	ciBuildDockerfile = 'java.Dockerfile'

	publisher = 'docker'
	dockerImageName = 'nemofficial/nis-client'
	dockerBuildArgs = "-f ./Dockerfile .."

	packageId = 'nem-nis'

	codeCoverageTool = 'jacoco'

	discordWebHookUrlId = 'CLIENT_DISCORD_WEB_HOOK_URL_ID'
}
